### ISSUE TITLE
PHP Fatal error:  require_once()

### ISSUE THREAD

**Issue by jimains** [magento-hackathon/MageBehat#3]
I get the following after following the install instructions: 
PHP Fatal error:  require_once(): Failed opening required '..../magento/lib/autoload.php'

**Comment by Schrank** [comment]
Thanks for the bug report, but you missed a lot of informations, there should be a stacktrace and a file and line number to the error.

Did you install the module with composer? composer should theoretically create the lib/autoloader.php.

P.S. I have no clue about all this :)

**Comment by jimains** [comment]
Ah yes, I see now. Apologies, I am new to composer but have reinstalled and no longer have this error. 

Many thanks for the response, I hope to contribute in the future :)
